<template>
  <div class="report-container">
    <button @click="generatePDF" class="btn">
      Generate Night Audit Report PDF
    </button>
  </div>
</template>

<script>
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default {
  name: "AuditReport",
  methods: {
    generatePDF() {
      const doc = new jsPDF("landscape");

      // Header function
      const addHeader = () => {
        doc.setFontSize(18);
        doc.text("MyHotel - Night Audit Report", 140, 15, { align: "center" });
        doc.setFontSize(12);
        doc.text("Date: 2025-05-22", 140, 25, { align: "center" });
      };

      // === PAGE 1: Income & Expense Summary ===
      addHeader();

      doc.setFontSize(14);
      doc.text("Income Summary", 14, 40);
      autoTable(doc, {
        startY: 45,
        head: [["Payment Mode", "Amount"]],
        body: [
          ["Cash", "8512"],
          ["Card", "0"],
          ["Online", "0"],
          ["Bank", "0"],
          ["UPI", "0"],
          ["Cheque", "0"],
          ["City Ledger", "12768"],
        ],
        theme: "grid",
      });

      doc.setFontSize(14);
      doc.text("Expense Summary", 14, doc.lastAutoTable.finalY + 15);
      autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 20,
        head: [["Payment Mode", "Amount"]],
        body: [
          ["Cash", "0"],
          ["Card", "0"],
          ["Online", "0"],
          ["Bank", "0"],
          ["UPI", "0"],
          ["Cheque", "0"],
        ],
        theme: "grid",
      });

      // === PAGE 2: Profit & Loss Summary ===
      doc.addPage();
      addHeader();
      doc.setFontSize(14);
      doc.text("Profit & Loss Summary", 14, 40);
      autoTable(doc, {
        startY: 45,
        head: [["Category", "Amount"]],
        body: [
          ["Profit", "8512"],
          ["Loss", "0"],
          ["City Ledger", "12768"],
        ],
        theme: "grid",
      });

      // === PAGE 3: Transaction Details ===
      doc.addPage();
      addHeader();
      doc.setFontSize(14);
      doc.text("Transaction Details", 14, 40);
      autoTable(doc, {
        startY: 45,
        head: [
          [
            "#",
            "Date",
            "Rev. No",
            "Room",
            "Guest",
            "Cash",
            "Card",
            "Online",
            "Bank",
            "UPI",
            "Cheque",
            "City Ledger",
          ],
        ],
        body: [
          [
            "1",
            "2025-05-22",
            "5",
            "204",
            "Mikayla",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "4256",
          ],
          [
            "2",
            "2025-05-22",
            "4",
            "206",
            "Kylan",
            "4256",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
          ],
          [
            "3",
            "2025-05-22",
            "3",
            "208",
            "Dawn",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "4256",
          ],
          [
            "4",
            "2025-05-22",
            "2",
            "102",
            "Fredericka",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "4256",
          ],
          [
            "5",
            "2025-05-22",
            "1",
            "203",
            "Murphy",
            "4256",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
          ],
        ],
        theme: "grid",
      });

      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.text(`Page ${i} of ${pageCount}`, 285, 200, { align: "right" }); // Adjusted
        doc.text("Generated by MyHotel System", 14, 200);
      }

      doc.save("Night_Audit_Report_2025-05-22.pdf");
    },
  },
};
</script>
