name: Deploy to DigitalOcean

on:
  push:
    branches:
      - v1 # Trigger deployment on push to v1 branch
    paths:
      - frontend/** # Only trigger deployment when changes are made in the frontend directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd frontend  # Change to the frontend directory
          npm install  # Install dependencies

      - name: Create Build
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          cd frontend  # Change to the frontend directory
          npm run build || { echo "Build failed"; exit 1; }
      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Install SSH client and sshpass if necessary
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Backup and deploy commands
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SERVER_IP" '
            # Backup existing app if it exists
            if [ -d /var/www/myhotel2cloud/frontend/.nuxt ]; then
              CURRENT_DATE=$(date +"%Y%m%d");
              cp -r /var/www/myhotel2cloud/frontend/.nuxt /var/www/myhotel2cloud/frontend/.nuxt-version-$CURRENT_DATE;
            fi

            # Pull the latest changes
            cd /var/www/myhotel2cloud
            git stash && git pull origin v1  # Adjust branch name if necessary
          '

          # Upload new build files
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r frontend/.nuxt/* "$SSH_USERNAME@$SERVER_IP:/var/www/myhotel2cloud/frontend/.nuxt/"

          # Reload the PM2 process on the server
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SERVER_IP" '
          pm2 reload 0
          '
